### ISSUE TITLE
Problem with order of annotations

### ISSUE THREAD

**Issue by mhsano** [pybel/pybel#134]
Hi,
We have a lot of legacy BEL content  from commercial providers which we would like to convert into JSON and other formats.
In cases where we have statement groups with annotations on e.g. species before  evidence or citation  annotations  e.g. in
 
SET Species = 9606" 
SET Evidence = "..."
SET Citation = "..."

we get a  MissingCitationException:

MissingCitationException: Missing citation; Can't parse : SET Species = 9606

If we start with evidence and citation annotations it works fine. 
e.g.:
SET Evidence = "..."
SET Citation = "..."
SET Species = 9606"

**Comment by cthoyt** [comment]
This is intended behavior. 

While BEL's specification doesn't *explicitly* state that this is a rule, it's a bit of nonsense to make annotations without making a reference to a citation first. BEL should be readable in a top-to-bottom manner, so we decided to enforce that a Citation is already set before making any other annotations or assertions, with the exception of `SET STATEMENT_GROUP = "ABC"`

We would rather not begin to add features that undermine the quality standards of BEL and readability of BEL documents, but we also don't want to make you waste a lot of good peoples' time. How frequent of an issue is this, and how much person-time do you think it would take to fix these issues?

If you're running the command line tool, you can add the flag `-v` or double `-v -v` to get a summary of the errors at the end of the module. Alternatively if you're in the python REPL or Jupyter notebook, our module [pybel-tools](http://pybel-tools.readthedocs.io/en/latest/) provides  functions to summarize errors. See our documentation on Read the Docs for [pybel_tools.summary.count_error_types()](http://pybel-tools.readthedocs.io/en/latest/summary.html#pybel_tools.summary.count_error_types)

**Comment by mhsano** [comment]
From this particular provider we have >1.000.000 statements and a large part will be affected. 
I will check with our provider if they can change this in the next release they will ship.

In general we are dealing with BEL content from various sources that is not "perfect" BEL but still provides value to us and we would not like to loose these statements. In many cases we will not be able to convince an external vendor to "correct" a significant part of a knowledge base that has been currated over the last 10-15 years. Would it be possibe to have an option for less strict parsing in one of the next realeases?

**Comment by cthoyt** [comment]
Yes, I will take care of this. I could change some of the logic in `pybel.parser.ControlParser` to allow for toggling between the standard mode where citations clear all annotations (and are generally better for identifying errors) and a strict mode that assumes all `UNSET` annotations are done properly, and does not automatically clear citations. However, in this scenario, I can imagine that BEL documents produced without great care would cause even more issues that we would unfortunately never be able to catch. 

Additionally, I don't think it would be so difficult to write a script that solves this issue programatically. It could find all groups of lines that don't begin with a `SET` or `UNSET` keyword, then reorder the following lines that do begin with `SET` before the next group that doesn't begin with those. This could be an easy, short term solution that you can do yourself. If you have the time, it would be a great contribution for `pybel_tools`!

For piece of mind, I would suggest asking your future providers to check either the warnings from the compiler provided in `pybel` or the experimental [web-based validator](https://github.com/cthoyt/pybel-web-validator/)

**Comment by cthoyt** [comment]
Okay this wasn't so tricky to do, but testing it will be hugely time consuming, so I'll let you try it and give me some feedback.

1. Get on the development branch (see the [installation documentation](http://pybel.readthedocs.io/en/latest/installation.html#get-the-latest))
2. When you're loading your graph using something like `pybel.from_path` you'll need to set the `citation_clearing` keyword to `False`. See the docs on the [BELGraph class](http://pybel.readthedocs.io/en/latest/datamodel.html#pybel.BELGraph) for an explanation of the keyword arguments, then apply them in your preferred `pybel.io` function outlined in the [input/output documentation](http://pybel.readthedocs.io/en/latest/io.html)

**Comment by mhsano** [comment]
It did not change a lot. I still get serveral warnings including a "missing evidence..." warning which is strange as there a "SET Evidence = ..." in the statement block:

WARNING:pybel.graph:Line 0000037 - MissingCitationException: Missing citation; can't parse: SET Species = "9606"
WARNING:pybel.graph:Line 0000039 - MissingCitationException: Missing citation; can't parse: SET TrustLevel = "high"
WARNING:pybel.graph:Line 0000045 - MissingSupportWarning: Missing evidence; can't add: abundance(....

**Comment by cthoyt** [comment]
The issue was with adding evidence, which also was checking that a citation was set first. I fixed that, and added some unit tests with a few permutations of adding citations, evidences, and annotations in different orders. Everything should be fine now for statements like:

```python
g = pybel.from_path('~/dev/bms/aetionomy/parkinsons.bel', citation_clearing=False)
```

Please let me know if that solves the issue :)

**Comment by mhsano** [comment]
It works! Thanks
Is it possible to set 'citation_clearing' also as a command-line option?

**Comment by cthoyt** [comment]
Yes, of course!

**Comment by cthoyt** [comment]
Is there anything I missed? I've already released this on CheeseShop as [v0.4.0](https://pypi.python.org/pypi?name=PyBEL&version=0.4.0&:action=display) and am getting ready for the first patch v0.4.1

**Comment by dexterpratt** [comment]
Thanks, I just ran into this with the TR test files for Metabase in BEL!  Now it works :-)

**Comment by mhsano** [comment]
It works!
