### ISSUE TITLE
Should Processes/Transformations be allowed in composites?

### ISSUE THREAD

**Issue by mhsano** [pybel/pybel#138]
Hi,

we get a parser failure for statements with compositeAbundance terms that include a bp() or path() term
a hypot. example: 

compositeAbundance(a(PCHEMID:123),bp(radiation)) decrease path(proliferation)
 
I am not sure if this is a valid BEL statement or a problem with the parser?

Thanks in advance....

**Comment by cthoyt** [comment]
Under the BEL specification, biological process and pathology nodes do not qualify as abundances. Composites and complexes can only accept abundances as their arguments. 

However, this is a compelling example. Do you have other scenarios where this strict rule limits expressing reasonable statements?

Maybe there are other examples where two biological processes synergize to increase a pathology, or something else, perhaps?

**Comment by mhsano** [comment]
We have multiple statements inour KAMs  that link a treatment to a process. Mostly things like radiation, chemotherapy, bariatric surgery, .... 
All are expressed as e.g.  compositeAbundance(treatment,chemotherapy) affects ....

In addidion we have statements expressing an abundance change/treatment in the context of a particluar pathology:
complexAbundance(PCHEM:1234,path(Diabetes))  decreases bp(...).

I assume these kind of statements could be converted into:
SET Disease = "Diabetes"
a(PCHEM:1234)  decreases bp(....)

**Comment by cthoyt** [comment]
@mhsano Hi Manfred, sorry this issue really got lost for a long time. Maybe we could move this discussion about language evolution over to https://github.com/belbio/bep.

**Comment by cthoyt** [comment]
I'm doing a bit of "winter cleaning" so if this continues to be an issue we can discuss it more on a new issue in https://github.com/belbio/bep
