### ISSUE TITLE
Add column names to constants

### ISSUE THREAD

**Issue by LeKono** [pybel/pybel#139]
We should consider adding the column names to a `constants.py` file. Would help with the creation of insert dictionaries.

**Comment by cthoyt** [comment]
Can you specify the database-side name for a given column in the Column() function by giving it a string, so it doesn't have to introspect on the name of the python variable it's being stuck into?

**Comment by LeKono** [comment]
Yes. And because the column names are used to create some insert dicts and also change some time it would be usefull I would say.

**Comment by cthoyt** [comment]
Agreed. Lets do this together next week. There quite a bit of housekeeping to do now for 0.4.3 release
