### ISSUE TITLE
Rewrite to_csv

### ISSUE THREAD

**Issue by maximilianh** [pybel/pybel#201]
for some reason the way you write the csv file does not produce valid json:

e.g. this string:

'evidence': 'Coordinate regulation of intracellular signaling pathways is central to the ability of mitogens and oncogenes to promote cell cycle progression (24). Two pathways thought to play an important role in committing quiescent cells into S phase are the RAS-activated RAF-MEK-extracellular signal-regulated kinase (ERK) and phosphatidylinositol 3'-kinase (PI3'- kinase)-PDK1-AKT pathways (35, 36). These pathways are reported to influence the expression, activity, or subcellular localization of key componen

The single quotes should be escaped, if you write with json or just plain repr(). But they're not, weird enough.

**Comment by maximilianh** [comment]
e.g. this line is the problem:

SET Evidence = "Coordinate regulation of intracellular signaling pathways is central to the ability of mitogens and oncogenes to promote cell cycle progression (24). Two pathways thought to play an important role in committing quiescent cells into S phase are the RAS-activated RAF-MEK-extracellular signal-regulated kinase (ERK) and phosphatidylinositol 3'-kinase (PI3'- kinase)-PDK1-AKT pathways (35, 36). These pathways are reported to influence the expression, activity, or subcellular localization of key components of the cell cycle machinery such as cyclins, cyclin-dependent kinases (CDKs), and CDK inhibitors (CKIs) leading to the appropriate activation of E2F transcription factors (50, 51). In addition to sensing the activation of specific signaling pathways, cells are also able to integrate the extent and timing of signal pathway activation and convert that information into an appropriate biological response (32, 48, 64, 66). For example, depending on the level of expression or activation, activated RAS can promote either cellular immortalization, oncogenic transformation, or cell cycle arrest in the same cell type (20, 48, 64, 66). Under these circumstances, RAS (or RAF)-induced cell cycle arrest is mediated by induced expression of CKIs of the INK4 or CIP/KIP family (29, 37). Interestingly, activation of \"parallel\" signaling pathways can modify the ability of RAS to regulate the G0-G1-Sphase cell cycle transition. For example, RAS-induced cell cycle arrest in Swiss 3T3 cells is prevented by coactivation of Rho signaling pathways (9, 43)."

**Comment by maximilianh** [comment]
This may be a bug in nx.write_edgelist https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.readwrite.edgelist.write_edgelist.html

called in io/extras.py function to_csv

**Comment by cthoyt** [comment]
As you probably saw in my code, the export functions in `pybel.io.extras` only consists of some thing wrappers around the `networkx` functions. I'm not dealing with JSON at myself, and only use the function `pybel.utils.flatten_dict` to get everything in a flat format so `networkx.write_edgelist` can take care of the rest.

I added the `data` argument to the wrapper (I actually think this is new since I wrote this function originally!) which should give you some finer granularity over which edges.

To be honest, these functions aren't tested so much because I don't think I will ever use them myself. But, if you have a reason to use CSV instead of one of the other graph formats, I'm curious to know what it is and I can put some more time into it.

**Comment by maximilianh** [comment]
Yes, I see, networkx cannot deal with "'" characters in the text. It only escaped double quotes.

The CX format is very difficult to parse for me. It's not meant to be easy to parse but its main aim is to be streamable and it's a reaction format mixed in with graphical attributes. I really prefer the CSV, it's completely easy to parse. 

Can you tell me what the order of the fields is? I imagine it's source, target, attributes and not target , source, attributes ? I am reading over a few example reactions and the order it not clear to me... sometimes the order that I infer in the text looks like it should be the opposite...

**Comment by maximilianh** [comment]
BTW your library was a life saver for me. the to csv function made it pretty easy to add openBEL to my network viewer, without it, I would have probably never added the OpenBEL large corpus to my collection of dozens of databases.

**Comment by cthoyt** [comment]
It looks like `nx.write_edgelist` really doesn't do a very good job at all outputting the data. I think it might be a good idea to rewrite this myself :)

Also, if your goal is to import lots of networks from different places, check out the [Causal Biological Network Database](http://causalbionet.com/) which distributes BEL documents in the JGIF format. You can download the whole dump from the main page and parse the JGIF serialization of BEL with the PyBEL functions listed here: http://pybel.readthedocs.io/en/latest/io.html#json-graph-interchange-format

**Comment by maximilianh** [comment]
Nice find, thanks! I have never heard of CBN before! I wonder if it's a lot
bigger than OpenBEL?

Hard to tell from their download, I'm just getting a 404 error...
http://causalbionet.com/Content/jgf_bulk_files/Human-2.0.zip

**Comment by cebel** [comment]
I asked causalbionet team for support. Link also not works for me. Will inform you about feedback

**Comment by cthoyt** [comment]
@maximilianh From what I understand, CBN was produced during a collaboration between ex-Selventa, Fraunhofer SCAI, and other teams during the Biocreative text mining challenge. The OpenBEL stuff is also from Selventa's publications on BEL, so it's possible there's some overlap.

@cebel I have a copy on my computer. I put it on BMS.
