### ISSUE TITLE
Can pathologies be the subject of causal statements?

### ISSUE THREAD

**Issue by norafilep** [pybel/pybel#210]
In case of head injuries (as an example) it could make sense to use pathologies as subject of causal statements. Or am I wrong?

Or when one disease cause an other one, like Traumatic Brain Injury causes Post-traumatic epilepsy.

**Comment by cthoyt** [comment]
I agree that it makes sense to talk about phenotypes/pathologies this way.

Unless I forgot or made a mistake, it should be special cased to only be an issue if a biological process or pathology is the subject of a causal relationship with a molecular entity. I don't think that saying something like `path(TBI) increases r(YFG)` is a reasonable way to talk about it. I would much rather see statements like `path(TBI) positiveCorrelation r(YFG)` in these situations
