### ISSUE TITLE
Compilation of the warnings received from PyBel which I believe should not be recognized as such

### ISSUE THREAD

**Issue by ddjukic** [pybel/pybel#214]
Hello everyone,

The nature of these might be fairly diverse so if you'd like me to categorize them somehow or something like that, please let me know.

**BEL line:**

bp(TBIBP:anesthesia) -> a(TBIA:"total choline vs total creatine ratio") 

**Warning**: 

"anesthesia" is not in the TBIBP namespace

**Comment:**

This is a frequent warning related to both of our custom namespaces (TBIBP and TBIA); the highlighted term is, in fact, in the namespace but the parser still cannot find it.

**BEL line:**

p(HGNC:GSK3A) -- bp(TBIBP:"tau hyperphosphorylation")

**Warning:**

BiologicalProcess TBIBP:tau hyperphosphorylation should be encoded as one of: Complex, miRNA, Gene, RNA, Protein, Abundance

**Comment:**

As the purpose of the namespace is to hold biological processes, annotating terms as such should be allowed; in this case I could also use general "Abundance" category but it doesn't seem quite as correct.

**BEL line:**

composite(bp(TBIBP:anesthesia), path(MESHD:"Brain Injuries, Traumatic")) -> a(TBIA:"N-acetylaspartate and N-acetylaspartylglutamate vs total creatine ratio")

**Warning:**

Unable to parse line

**Comment:**

I am aware that nested statements are deprecated but composite abundance is not really a nested statement, right? I am not sure why this line is not parseable.

Thanks in advance for looking into these,
Dejan

**Comment by cthoyt** [comment]
Link to the namespace? I believe Nora had this issue already and some of the semantic warnings were because the namespace was written improperly

**Comment by cthoyt** [comment]
Biological processes can't appear in composites. See the bel specification.

**Comment by cthoyt** [comment]
In that case, you should use an annotation to set the disease

**Comment by ddjukic** [comment]
Yeah, I've checked the link to the namespace 5 times now; the model in question is 27779341 so you could check it yourself if you wish, there might be something I keep missing.

Alright, I'll work around that somehow, thanks!
