### ISSUE TITLE
Cross reference INDRA Protein Modification

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#221]
make sure pybel supports everything in this list http://indra.readthedocs.io/en/latest/modules/statements.html

Extra credit: cross reference with SBO

**Comment by cthoyt** [comment]
Question for @johnbachman and @bgyori:

The BEL 2.0 specification has synonyms `ADP-ribosylation`, `ADPRib`, and`adenosine diphosphoribosyl`. Do these directly correspond to INDRA's [ribosylation statement](http://indra.readthedocs.io/en/latest/modules/statements.html#indra.statements.Ribosylation)?

More specifically - is ADP ribosylation too specific? If that's the case, I can add a more general `ribosylation` term.

Otherwise, this issue is set and I'm ready to push the new version of PyBEL to PyPI with all the updates for INDRA.

**Comment by bgyori** [comment]
Yes, I think they are the same thing

**Comment by cthoyt** [comment]
Brilliant
