### ISSUE TITLE
Issue with cascading on properties

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#225]
This needs better test coverage, because the introduction of the test in d5da1498e1a9cac5f3dd56a79eb32a10063191af using the `FleetingTemporaryCacheMixin` makes everything fail (RE: https://travis-ci.org/pybel/pybel/jobs/275806438)

**Comment by LeKono** [comment]
This should be fixed now and may be closed when merging to dev.

**Comment by cthoyt** [comment]
Please make a Pull Request
