### ISSUE TITLE
Write-up on Why Not RDF

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#27]
This issue used to be called 'Export to RDF', but I think we should assemble our thoughts on why RDF is a bad way to do data interchange for this kind of data, and add that to the Design Choices section of the documentation

**Comment by LeKono** [comment]
I don't know if the most simple structure (RDF-trible) could be used to do something?
 `(Protein) - INNTERACTS - (Protein)`
Like basic information store

**Comment by cthoyt** [comment]
Yeah you could do that, but then you lose all the nice annotations. Remember there's no way to represent annotations on to this edge without doing some hackey stuff with blank nodes - just check some of the BEL RDF examples from @OpenBEL's bel.rb repository
