### ISSUE TITLE
Improve efficiency of network drop

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#270]
Right now, it's so slow that the Selventa large corpus can't be dropped in a reasonable time. 

Need to get smarter about building queries that efficiently find edges that are in a give network (to be dropped) but not in any other ones, then drop them.

Then, drop the network.

**Comment by scolby33** [comment]
You'll have to test this with the new code from #319 to see if it's fast enough. If it's not, there's faster but more dangerous (read: we need to be more careful) ways to do it.
