### ISSUE TITLE
Return inside generator error in Python 2

### ISSUE THREAD

**Issue by bgyori** [pybel/pybel#277]
When installing either the `develop` or the `update-networkx` branch of pybel inside a Python 2.7 virtualenv, `import pybel`, and more specifically, `from pybel.struct.filters import edge_flters` errors as follows:
```
  File "/Users/ben/.virtualenvs/py2/lib/python2.7/site-packages/pybel/struct/filters/edge_filters.py", line 105
    yield u, v, k
SyntaxError: 'return' with argument inside generator
```

**Comment by bgyori** [comment]
Would changing https://github.com/pybel/pybel/blob/update-networkx/src/pybel/struct/filters/edge_filters.py#L100 
from
```
return graph.edges(keys=True)
```
to
```
for e in graph.edges(keys=True):
    yield e
```
work? I don't fully understand the situation so this is just a guess.

**Comment by cthoyt** [comment]
That's so weird - I was able to reproduce your problem using tox, and your solution fixes it

**Comment by bgyori** [comment]
Great, that fixed it, thanks!
