### ISSUE TITLE
Drop python2 support

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#285]
- [x] take python2 checks away from Travis and Appveyor
- [x] remove backports in `setup.cfg`
- [ ] remove references to `six`

Side note: the infrastructure running BEL Commons is only running py34, so we need a plan for upgrading that first

**Comment by cthoyt** [comment]
@johnbachman @bgyori how would this impact INDRA?

**Comment by cthoyt** [comment]
Ping @bgyori @johnbachman any new thoughts on the possibility of dropping Python 2?

**Comment by bgyori** [comment]
We'll keep support for the time being as long as we don't run into something that would require too much extra work to make cross-compatible. However, as far as specific input sources and output assemblers go, we can handle dependencies that aren't Python 2 compatible, and so, though a little bit inconvenient, it would be okay for us if `pybel` became Python 3 only.
