### ISSUE TITLE
Create JSON Schema for PyBEL Nodes

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#296]
A JSON schema is a JSON document that describes the schema other JSON documents should have. Since PyBEL's nodes have a well-defined schema (see: https://pybel.readthedocs.io/en/latest/datamodel.html#nodes), it would be a good idea to generate a JSON schema describing these.

## Resources

- More information can be found at http://json-schema.org. 
- A similar effort was done at http://jsongraphformat.info by William, but it's a bit out of date at this point, and the schema is very different from PyBEL. 

## To Do

- [x] Generate JSON schema
- [x] Write unit tests with several different nodes generated by `pybel.dsl` and validate against this schema using [`jsonschema`](https://python-jsonschema.readthedocs.io/en/latest/)

**Comment by cthoyt** [comment]
@AgenoDrei what's the status?

**Comment by AgenoDrei** [comment]
Hey :) I completed a schema for all kind of nodes. Only the representation of edges is still missing. Sadly I have to focus now on the gitlab issue I got from Marc. So it could take same time to complete the edge json schema.

**Comment by AgenoDrei** [comment]
Yeah, everything should work :)

Am Do., 10. Jan. 2019 um 15:29 Uhr schrieb Charles Tapley Hoyt <
notifications@github.com>:

**Comment by cthoyt** [comment]
Closed by #450
