### ISSUE TITLE
AttributeError: module 'pybel' has no attribute 'readstring'

### ISSUE THREAD

**Issue by muu4649** [pybel/pybel#309]
Hi !
I have a question about pybel.
I installed below.

conda install -c bioconda pybel 

and I finished installing pybel and OpenBabel, but 

$ python generate.py 
infer_central_dogmatic_translations is deprecated. please migrate to enrich_proteins_with_rnas
infer_central_dogmatic_transcriptions is deprecated. please migrate to enrich_rnas_with_genes
infer_central_dogma is deprecated. please migrate to enrich_protein_and_rna_origins
collapse_by_central_dogma is deprecated. please migrate to collapse_to_genes
prune_central_dogma is deprecated. please migrate to prune_protein_rna_origins
Traceback (most recent call last):
  File "generate.py", line 70, in <module>
    main()
  File "generate.py", line 31, in main
    pymol = pybel.readstring('smi', smile)
AttributeError: module 'pybel' has no attribute 'readstring'

I want to compile this code https://github.com/cameronus/coulomb-matrix.git.

what should I do?
Please answer if you care. Thank you.

**Comment by cthoyt** [comment]
Sorry for the late response, but I think you've discovered a small name conflict between this package (for biological expression language) and the Open Babel python wrapper.
