### ISSUE TITLE
Print functions incompatible with Python 2.x

### ISSUE THREAD

**Issue by bgyori** [pybel/pybel#333]
In commit 768228cea4a0fca28339dbc228b2ba4b46379e25, these new lines:
https://github.com/pybel/pybel/blob/develop/src/pybel/struct/graph.py#L1027-L1031
are not 2.x compatible and cause syntax errors. Not that I use Python 2 but our automated tests are failing :)

**Comment by cthoyt** [comment]
Oops. Should be all fixed. I’ll close when travis goes from failing (it caught this too) to passing

**Comment by cthoyt** [comment]
Closed by 9b8e0fd
