### ISSUE TITLE
Fix permission for *.json (should not be executable)

### ISSUE THREAD

**Issue by smoe** [pybel/pybel#352]
```
$ ls -l "./src/pybel/testing/resources/bel/Cytotoxic T-cell Signaling-2.0-Hs.json"
-rwxr-xr-x 1 moeller moeller 435576 Oct 16 17:48 './src/pybel/testing/resources/bel/Cytotoxic T-cell Signaling-2.0-Hs.json'
```
Please kindly "chmod -x" that as this is nothing to execute.

<ignore>
It follows some bike shedding. Please ignore if not in some good mood. I am only mentioning it since there is a chance you touch the file anyway. For scripting these blanks are somewhat unfortunate to use. Is it thinkable that you tr " " "_" them? Also you have the hyphen/dash "-" as a separater in later parts of the filename. Maybe "Cytotoxic_T-cell_Signaling_2.0_Hs.json" is how to be consistent - except that there is no dash between "T" and "cell" in English but a blank.
</ignore>

Cheers,

Steffen

**Comment by cthoyt** [comment]
I agree that this JSON file has a funny nomenclature. It actually comes from the [Causal Biological Networks Database](http://causalbionet.com). Here's a link to the [CYTOTOXIC T-CELL SIGNALING V2.0](http://causalbionet.com/Home/NetworkVisualization/#/!/networkGraph?ID=cytotoxic_t_cell_signaling_2.0_hs) download that yields this file. I chose to keep the original file name.
