### ISSUE TITLE
No attribute readfile

### ISSUE THREAD

**Issue by yuanyingfang23** [pybel/pybel#379]
Exception has occurred: AttributeError
module 'pybel' has no attribute 'readfile'

**Comment by cthoyt** [comment]
Hi @yuanyingfang23, are you looking for the [python wrapper](https://github.com/openbabel/openbabel/tree/master/scripts/python) around OpenBabel?

**Comment by yuanyingfang23** [comment]
Yes, because I am doing some tasks with chemical data.




Cheers,

Yingfang(James) Yuan

________________________________

**Comment by cthoyt** [comment]
I'm sorry about the confusion, but you've installed the wrong package. This repository is related to the Biological Expression Langauge (BEL).

You can uninstall this one with `pip uninstall pybel` then check out the https://github.com/openbabel/openbabel documentation on how to install their package
