### ISSUE TITLE
Segmentation fault (core dumped) - When large protein mol2 file were read

### ISSUE THREAD

**Issue by keisuke-yanagisawa** [pybel/pybel#386]
Dear Administrator, 

scPDB dataset provides protein structures by mol2 format.
To generate machine learning features I used pybel, but Segmentation fault has been occurred for large protein file.

Below is minimum code:
```py
import pybel
mol = next(pybel.readfile("mol2", "scPDB/1e1q_4/protein.mol2")) # Segmentation fault
```

My python environment is:
- anaconda3-2018.12 (installed by pyenv)
- openbabel 2.4.1 (conda-forge) was installed by `conda install`

I also attached corresponding URL to scPDB.
http://bioinfo-pharma.u-strasbg.fr/scPDB/SITE=1e1q_4

Thank you in advance!

**Comment by cthoyt** [comment]
Hi @keisuke-yanagisawa,

This repository is related to the Biological Expression Langauge (BEL), and you're probably looking for the OpenBabel documentation at https://github.com/openbabel/openbabel documentation or https://github.com/openbabel/openbabel/tree/master/scripts/python

**Comment by keisuke-yanagisawa** [comment]
Oh.., I'm sorry for my mistake.
