### ISSUE TITLE
Can not work on py3.7

### ISSUE THREAD

**Issue by Urheen** [pybel/pybel#389]
When I install on my environment with python 3.7, it showed the error:

![image](https://user-images.githubusercontent.com/27939296/64638075-17a8a800-d3d3-11e9-9203-5dc871f905b0.png)

**Comment by cthoyt** [comment]
Hi @Urheen, this screenshot really isn't enough information for me to give any help... what did you type before this?

**Comment by cthoyt** [comment]
Sorry but since there hasn't been a response in a while, I'm going to assume this was due to a bit of confusion with OpenBabel and close this issue. If I'm mistaken, I will happily re-open this issue and we can see if we can solve your problem :)
