### ISSUE TITLE
Make Logging Lazy Again

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#40]
Make all log statments use the `%` operator, because it's better. Example: `log.info('Log this: %s', this)`

- https://www.reddit.com/r/Python/comments/387oog/when_will_logging_use_newstyle_string_formatting/
- https://www.reddit.com/r/Python/comments/58l5aj/is_it_true_that_is_outdated/d91ov2b/

**Comment by cebel** [comment]
Hey, Charlie Great. I'm a big fan of percent
