### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by LeKono** [pybel/pybel#42]
Windows may not be the OS of choice for programmers but for other scientists and students it is often the OS to go. There is a problem in `requests_file` with local files on a windows machine. It can not handle the windows OS.sep becaus the url decoding is implemented with this statement: 

`path_parts = [unquote(p) for p in url_parts.path.split('/')]`.

Maybe this is not the most urgent 'bug' to handle. But it is a problem that we should take care of.

**Comment by cthoyt** [comment]
How would the code need to be different to make it work on windows?

Can you make a pull request on Requests-File to fix this?

**Comment by LeKono** [comment]
They just should use os.sep as a separator for the path decoding.

I'll also keep track on how PyBEL is running on Windows to find other compatibility issues.

**Comment by cthoyt** [comment]
Go open source! Everything's better when you're part of a teak

**Comment by cthoyt** [comment]
any updates?

**Comment by cthoyt** [comment]
I made a PR for this dashea/requests-file#6

**Comment by cthoyt** [comment]
Looks like this issue isn't a Windows problem, but you're building file paths in an illegal way. Best to look around and find a better URI builder sincerely `os` isn't built specifically for this.
