### ISSUE TITLE
Make PyBEL Python 3.6+

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#428]
@bgyori said that INDRA might not need to be python35 compliant anymore. If that's the case, then we can plan on a PyBEL release that will coincide with INDRA dropping support for py35/py36 as well

**Comment by bgyori** [comment]
We're about to drop support for Python 3.5, is there anything about 3.6 that you are tempted to be incompatible with?

**Comment by cthoyt** [comment]
Two of the nice things in Python 3.7+ is dataclasses (this has a [backport](https://pypi.org/project/dataclasses/), though) and improvements to annotations from [pep-0563](https://www.python.org/dev/peps/pep-0563/) (`from __future__ import annotations`) but that's not a dealbreaker.

**Comment by bgyori** [comment]
How about we support 3.6 on our end for now, and if you need dataclasses here, add the backport to pybel's setup.py to keep support for it?

**Comment by cthoyt** [comment]
Yeah, that's what I meant! 3.6 is no problem for me :)
