### ISSUE TITLE
from_graphdati() reads jgif network format, not graphdati nanopub format

### ISSUE THREAD

**Issue by djinnome** [pybel/pybel#441]
Hi @cthoyt 

BioDati exports  [graphdati nanopub format](https://github.com/graphdati/schemas/blob/master/nanopub_graphdati-1.1.0.yaml) files, but the [`from_graphdati()`](https://github.com/pybel/pybel/blob/master/src/pybel/io/graphdati.py#L228-L231) function expects jgif format.  See attached file for an example graphdati format file.

[MAPK-small.bel.graphdati.json.txt](https://github.com/pybel/pybel/files/4674486/MAPK-small.bel.graphdati.json.txt)

**Comment by cthoyt** [comment]
really funny stuff - I'm pretty sure they don't actually follow their own standard. The weekend I was working on this, the exporter was definitely half broken too, so I wasn't able to figure out edge cases.

I would suggest trying the [from_biodati()](https://pybel.readthedocs.io/en/latest/reference/io.html#pybel.from_biodati) and see if it works. You have to group all the nanopubs in to a network first and I think you need to copy the ID out of the URL since it might not be written anywhere on the page

**Comment by djinnome** [comment]
OK, I got BioDati to convert the nanopub to a network and exported as jgif. Now the problem appears to be that pybel does not recognize TAX as a valid namespace, as in the example:

`pop(TAX:"Severe acute respiratory syndrome coronavirus 2")`

neither does:
`pop(ncbitaxon:"Severe acute respiratory syndrome coronavirus 2")`

even though `ncbitaxon` is in the metaregistry.json and `TAX` is a synonym.

Any recommendations for the right namespace to recognize ncbi taxon id?




I am guessing that in version 2.2.0 of BEL, this would be the correct node name:

`pop(TAX:2697049 ! "Severe acute respiratory syndrome coronavirus 2")`


In any case, here is the file, the code and the error message:

[COVID-19-a-new-virus-but-an-old-cytokine-release-syndrome.short.jgif.txt](https://github.com/pybel/pybel/files/4704866/COVID-19-a-new-virus-but-an-old-cytokine-release-syndrome.short.jgif.txt)

```python
short_jgif = 'COVID-19-a-new-virus-but-an-old-cytokine-release-syndrome.short.jgif'  
il6_amp = pybel.from_jgif_file(short_jgif)
il6_amp
​```

```
INFO: [2020-05-29 17:51:57] pybel.parser.baseparser - streamlined BELParser in 1.86 seconds
---------------------------------------------------------------------------
UndefinedNamespaceWarning                 Traceback (most recent call last)
<ipython-input-13-8a4553023dd2> in <module>
      1 short_jgif = 'COVID-19-a-new-virus-but-an-old-cytokine-release-syndrome.short.jgif'
----> 2 il6_amp = pybel.from_jgif_file(short_jgif)
      3 il6_amp

</Users/zuck016/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/decorator.py:decorator-gen-813> in from_jgif_file(path)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/networkx/utils/decorators.py in _open_file(func_to_be_decorated, *args, **kwargs)
    238         # Finally, we call the original function, making sure to close the fobj
    239         try:
--> 240             result = func_to_be_decorated(*new_args, **kwargs)
    241         finally:
    242             if close_fobj:

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pybel/io/jgif.py in from_jgif_file(path)
    323     :param path: A path or file-like
    324     """
--> 325     return from_jgif(json.load(path))
    326 
    327 

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pybel/io/jgif.py in from_jgif(graph_jgif_dict, parser_kwargs)
    256 
    257         try:
--> 258             parser.bel_term.parseString(node_label)
    259         except NakedNameWarning as e:
    260             logger.info('Naked name: %s', e)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseString(self, instring, parseAll)
   1935             instring = instring.expandtabs()
   1936         try:
-> 1937             loc, tokens = self._parse(instring, 0)
   1938             if parseAll:
   1939                 loc = self.preParse(instring, loc)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1675             if self.mayIndexError or preloc >= len(instring):
   1676                 try:
-> 1677                     loc, tokens = self.parseImpl(instring, preloc, doActions)
   1678                 except IndexError:
   1679                     raise ParseException(instring, len(instring), self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   4235         for e in self.exprs:
   4236             try:
-> 4237                 ret = e._parse(instring, loc, doActions)
   4238                 return ret
   4239             except ParseException as err:

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1675             if self.mayIndexError or preloc >= len(instring):
   1676                 try:
-> 1677                     loc, tokens = self.parseImpl(instring, preloc, doActions)
   1678                 except IndexError:
   1679                     raise ParseException(instring, len(instring), self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   4235         for e in self.exprs:
   4236             try:
-> 4237                 ret = e._parse(instring, loc, doActions)
   4238                 return ret
   4239             except ParseException as err:

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1675             if self.mayIndexError or preloc >= len(instring):
   1676                 try:
-> 1677                     loc, tokens = self.parseImpl(instring, preloc, doActions)
   1678                 except IndexError:
   1679                     raise ParseException(instring, len(instring), self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   4235         for e in self.exprs:
   4236             try:
-> 4237                 ret = e._parse(instring, loc, doActions)
   4238                 return ret
   4239             except ParseException as err:

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1675             if self.mayIndexError or preloc >= len(instring):
   1676                 try:
-> 1677                     loc, tokens = self.parseImpl(instring, preloc, doActions)
   1678                 except IndexError:
   1679                     raise ParseException(instring, len(instring), self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   4050                     raise ParseSyntaxException(instring, len(instring), self.errmsg, self)
   4051             else:
-> 4052                 loc, exprtokens = e._parse(instring, loc, doActions)
   4053             if exprtokens or exprtokens.haskeys():
   4054                 resultlist += exprtokens

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1675             if self.mayIndexError or preloc >= len(instring):
   1676                 try:
-> 1677                     loc, tokens = self.parseImpl(instring, preloc, doActions)
   1678                 except IndexError:
   1679                     raise ParseException(instring, len(instring), self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   4443     def parseImpl(self, instring, loc, doActions=True):
   4444         if self.expr is not None:
-> 4445             return self.expr._parse(instring, loc, doActions, callPreParse=False)
   4446         else:
   4447             raise ParseException("", loc, self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1675             if self.mayIndexError or preloc >= len(instring):
   1676                 try:
-> 1677                     loc, tokens = self.parseImpl(instring, preloc, doActions)
   1678                 except IndexError:
   1679                     raise ParseException(instring, len(instring), self.errmsg, self)

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in parseImpl(self, instring, loc, doActions)
   4235         for e in self.exprs:
   4236             try:
-> 4237                 ret = e._parse(instring, loc, doActions)
   4238                 return ret
   4239             except ParseException as err:

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in _parseNoCache(self, instring, loc, doActions, callPreParse)
   1708                 for fn in self.parseAction:
   1709                     try:
-> 1710                         tokens = fn(instring, tokensStart, retTokens)
   1711                     except IndexError as parse_action_exc:
   1712                         exc = ParseException("exception raised in parse action")

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pyparsing.py in wrapper(*args)
   1314         while 1:
   1315             try:
-> 1316                 ret = func(*args[limit[0]:])
   1317                 foundArity[0] = True
   1318                 return ret

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pybel/parser/parse_concept.py in handle_identifier_qualified(self, line, position, tokens)
    117     def handle_identifier_qualified(self, line: str, position: int, tokens: ParseResults) -> ParseResults:
    118         """Handle parsing a qualified identifier."""
--> 119         return self._handle_identifier(line, position, tokens, key=NAME)
    120 
    121     def _handle_identifier(self, line: str, position: int, tokens: ParseResults, key) -> ParseResults:

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pybel/parser/parse_concept.py in _handle_identifier(self, line, position, tokens, key)
    123         namespace, name = tokens[NAMESPACE], tokens[key]
    124 
--> 125         self.raise_for_missing_namespace(line, position, namespace, name)
    126         self.raise_for_missing_name(line, position, namespace, name)
    127 

~/.pyenv/versions/anaconda3-2019.10/lib/python3.7/site-packages/pybel/parser/parse_concept.py in raise_for_missing_namespace(self, line, position, namespace, name)
     99         """Raise an exception if the namespace is not defined."""
    100         if not self.has_enumerated_namespace(namespace) and not self.has_regex_namespace(namespace):
--> 101             raise UndefinedNamespaceWarning(self.get_line_number(), line, position, namespace, name)
    102 
    103     def raise_for_missing_name(self, line: str, position: int, namespace: str, name: str) -> None:

UndefinedNamespaceWarning: "TAX" is not a defined namespace
```

**Comment by djinnome** [comment]
OK, found the code  for [declaring namespaces in jgif files](https://github.com/pybel/pybel/blob/master/src/pybel/io/jgif.py#L131) and [submitted a pull request](https://github.com/pybel/pybel/pull/442)

**Comment by djinnome** [comment]
Hmm... there should be 17 edges, but Pybel only parses 2.  

```python
short_jgif = 'COVID-19-a-new-virus-but-an-old-cytokine-release-syndrome.short.jgif'  
il6_amp = pybel.from_jgif_file(short_jgif)
il6_amp.summarize()
INFO: [2020-05-30 06:32:31] pybel.parser.baseparser - streamlined BELParser in 1.93 seconds
IL6-Amp vNone
Number of Nodes: 16
Number of Edges: 2
Number of Citations: 0
Number of Authors: 0
Network Density: 8.33E-03
Number of Components: 14
Number of Warnings: 0
```

Looking at `from_jgif()` it appears the problem is that the jgif file only contains a `nanopub_url`  key in the `metadata` dict, not an `evidences` key, so the only edges `from_jgif` captures are the `partOf` relations it automagically extracts from the `complex()` node.

However, when I ran `from_biodati()` I was able to get all 17 edges plus the two inferred edges.

So I will call it a win, and move on.  All the BEL statements are officially freed from BioDati.
