### ISSUE TITLE
Example from readme does not work / should be updated

### ISSUE THREAD

**Issue by shuvrobiswas** [pybel/pybel#448]
Hey guys,

Just installed the package (set up with fresh install of anaconda, on windows, python version 3.7.6, pybel version 0.14.10).

The example code from the readme uses the function from_url, which does not exist in this version, should be from_bel_script_url (which works for me).

```python
import pybel
url = 'https://raw.githubusercontent.com/pharmacome/knowledge/master/hbp_knowledge/proteostasis/kim2013.bel'
graph = pybel.from_url(url)
```

**Comment by scolby33** [comment]
Doctests might be a good idea for this in the future :)

**Comment by cthoyt** [comment]
@shuvrobiswas thanks for pointing that out, it's fixed now. Please let me know if you run into anything that's not clear - I'm happy to prioritize improvement of documentation or code that helps others.

@scolby33 I've actually started going down this road in PyBEL already in a few modules, but I'm not sure if it works on the README. I'll give it a try. The only other issue is this test would require hitting a live API... I don't want to anger GitHub

**Comment by shuvrobiswas** [comment]
Thanks @cthoyt will do - looking forward to playing around with this package 👍
