### ISSUE TITLE
write kekulised molecules

### ISSUE THREAD

**Issue by shalkya** [pybel/pybel#456]
Hello, it might be an issue with openbabel, but for now i am posting that here.
I have tried to write kekulised form of molecules in mol2 files with pybel.

I figured out a way to do that, but it feels very hacky : 

```
mol = next(pybel.readfile("mol2", f"{path}/{dataset}/{pdb}/{pdb}_ligand.mol2"))
mol.OBMol.Kekulize()
mol.write("mol2", f"{path}/{dataset}/{pdb}/{pdb}_ligand_kekulised.mol2", overwrite=True)
mol.OBMol.Kekulize()
mol.write("mol2", f"{path}/{dataset}/{pdb}/{pdb}_ligand_kekulised.mol2", overwrite=True)
```

As you can see, I am creating the file twice and I have to do `mol.OBMol.Kekulize()` twice too, in this specific order.
Creating the file only once, or not using (or only once) `mol.OBMol.Kekulize()` lead to write unkekulised form of the molecule.

Is it a bug on your side or i missed an option while writing down the mol2 files ?

**Comment by cthoyt** [comment]
Hi @shalkya, you seem to have confused our package with OpenBabel. Please check https://github.com/openbabel/openbabel/tree/master/scripts/python
