### ISSUE TITLE
Add Namespace Mapping Models and Manager

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#48]
The OpenBEL framework provides equivalence (`*.beleq`) files in the same format as the namespace (`*.belns`) and annotation (`*.belanno`) files. These files map each value to a hash that represents their "equivalence class"

Example: http://resources.openbel.org/belframework/20150611/equivalence/disease-ontology.beleq

- [x] Using the models in `pybel.manager.database_models` and I/O class `pybel.manager.database_models.DefinitionsCacheManager.py` built by @LeKono for the Definitions Cache Manager as a template, build a new `sqlalchemy` model to store this data.
  - This could be one table to represent "equivalence classes" and one to represent the many-to-one relation between `pybel.manager.database_models.Context` and the equivalence class
- [x] Identify relevant equivalence files from the 1.0, 2013, and 2015 releases of the [BEL Framework](http://resources.openbel.org/belframework)

**Comment by cebel** [comment]
In general we have a problem with ...
1. missing names in namespaces
2. wrong [classification](http://openbel-framework.readthedocs.io/en/latest/tutorials/building_custom_namespaces.html#my-understanding-entity-encoding) of names in namespace leads to parser error logs. example: **Inflammation** classified with **O** in **[MESHD](http://resource.belframework.org/belframework/20150611/namespace/mesh-diseases.belns)** namespace as ***path*** and not correctly with **B** as ***biological process***

Solution: own repository of namespaces?

**Comment by cthoyt** [comment]
Missing names: I don't need to be convinced. My thoughts are in the [design choices section](http://pybel.readthedocs.io/en/latest/design.html#why-not-rdf) of the docs...  definitely an issue for another day

I think the line between biological processes and pathologies are often very blurred, and definitely subjective. This is definitely true for the case for whether inflammation is a pathology or biological process, and maybe also true in general. 

Can you give an example where there is a substantial difference in the way analyses are performed that's affected by this difference?

**Comment by cthoyt** [comment]
nanditha why don't you give this a try while waiting for the data manager and pybel-API prerequisites

**Comment by cebel** [comment]
@cthoyt : What you mean with **this** in the comment to nanditha?

**Comment by cthoyt** [comment]
@cebel Nanditha's task for the flask-restless API on top of the data manager is dependent on @LeKono's work. @NandithaMallesh if you're feeling motivated, you could work on this while you're waiting and that would be really helpful! Otherwise, Andrej could get to it later, or I'll do it when I need it.

**Comment by NandithaMallesh** [comment]
@cthoyt : i can work on this. But define "this" :) We can discuss it later today and maybe you can explain what you are thinking when you say this :)

**Comment by cthoyt** [comment]
Completed with efbda0d63e87ebfba61ac64d0c6da03d49307d00
