### ISSUE TITLE
Convert .Molecule or OBMol to SMILES

### ISSUE THREAD

**Issue by LivC182** [pybel/pybel#486]
Hi I am using your library to read pdb files from file and transform that file into a SMILES string:
`mol = readfile("pdb", path).__next__()`
and all i can see is `mol.formula`. However, if I do:
```
mol = readfile("pdb", path).__next__()
print(mol)
```
Gives me this output which contains a SMILE string: 
`[NH3]CC(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@H](C(=O)O)Cc1ccccc1)CS)CCCNC(=[NH2])N)CCCNC(=[NH2])N)CCCNC(=[NH2])N)CCCC[NH3])CC(C)C)CO)CCC(=O)N)C(C)C.O.O      path_to_pdb.pdb`

I was wondering if I can get the SMLES string from: `mol = readfile("pdb", path).__next__()` as well
Looks like `str(mol)` does the trick but is not very clean. since it also has some other chars like '\n' and '\t'

**Comment by cthoyt** [comment]
Hi @LivC182 , you seem to have confused our package with OpenBabel. Please check https://github.com/openbabel/openbabel/tree/master/scripts/python
