### ISSUE TITLE
Graph Data Management

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#49]
This is the monolithic to-do for the data manager portion of the project. This consists of translating the `Django` models used in the AETIONOMY Knowledgebase to use `SQLlchemy`. 

For the first try, do **NOT** focus on speed. We need a working implementation first before optimizing. This should all be done in beautiful, idiomatic python, and take full advantage of the `SQLAlchemy` ORM. This also means that `pandas` is unacceptable.

## Production ready

- [x] Add model for network metadata. Include the pickled graph. (`pybel.manager.models.Network`)
- [x] Input and output of network object in Graph Cache Manager (`pybel.manager.graph_cache.GraphCacheManager`)

## Still needs reinvestigation

- [x] Add models to `pybel.manager`
- [x] Implement `pybel.to_database(belgraph, conn_str)`
- [x] Implement `pybel.from_database(conn_str)`

Reinvestigate all code:
- [ ] Add docs to all models
- [x] Add ORM information, like `relationship()` to automatically make joins
- [x] Use proper session querying, like `session.query(models.Namespace).filter(models.Namespace.keyword == 'HGNC').one()` and transaction management at the `session` level

**Comment by LeKono** [comment]
The BelDataManager has the function `bdm.store_graph(pybel_graph, graph_label, graph_name=None)` and `bdm.load_graph(graph_label)`. Graph label is used as unique identifier to make multiple graphs accessable. That way the user also does not need to take care of 'where should if pickle this to?'. 

Also the method `bdm.show_stored_graphs()` returns a list of all graph_labels in the database.

This can be used as groundwork for the future user management system.

In addition we have to clarify (tomorrow) how to handle different versions of namespaces in the relational store.
