### ISSUE TITLE
attribute error for pybel

### ISSUE THREAD

**Issue by ahmed4899** [pybel/pybel#500]
I was trying to run a command for preparecovalent.py on python 3.10.4, and I get this error:

Traceback (most recent call last):
  File "/home/ahmed/Downloads/adCovalentDockResidue/adcovalent/prepareCovalent.py", line 37, in <module>
    ob = pybel.ob
AttributeError: module 'pybel' has no attribute 'ob'

I can't find any ob attributes in my files.

**Comment by cthoyt** [comment]
Hi @ahmed4899, you seem to have confused our package with OpenBabel. Please check https://github.com/openbabel/openbabel/tree/master/scripts/python.
