### ISSUE TITLE
Support for SET SupportingText

### ISSUE THREAD

**Issue by cebel** [pybel/pybel#56]
SupportingText (BEL 2.0, examples http://openbel.org/language/web/version_2.0/bel_specification_version_2.0.html) is not accepted instead of Evidence (BEL 1.0)

**Comment by cthoyt** [comment]
You have to be a bit more clear... is there an issue here? What's the action that needs to be taken?

**Comment by cebel** [comment]
**SET SupportingText** should be accepted instead of **SET Evidence**. In the moment the parser marks this as "Illegal annotation".

example:
SET Citation = {"PubMed", "Nat Cell Biol 2007 Mar 9(3) 316-23", "17277771"}
SET SupportingText = "Here, we identify PRAS40 (proline-rich Akt/PKB substrate 40 kDa) as a novel mTOR binding partner"

**Comment by cthoyt** [comment]
oh that's wild! I don't know how I never noticed that while reading through the spec before... Will fix with 0.2.6

**Comment by cthoyt** [comment]
Also, should all instances of `SET Evidence` be translated to `SET SupportingText`? @lekono will need to watch out for this and modify the data model
