### ISSUE TITLE
Add loc() to abundance()

### ISSUE THREAD

**Issue by cebel** [pybel/pybel#57]
following valid BEL statement: 

a(CHEBI:"calcium(2+)", loc(GOCC:"endoplasmic reticulum")) -> bp(GOBP:"cell cycle arrest")

... logs a **general parser failure**

* subject of the statement is an example from 2.2.4. Cellular location (BEL 2.0 documentation)
* reason is not identified in the moment
* all names are valid in the below listed namespaces

used namespaces are:
DEFINE NAMESPACE GOCC AS URL "http://resource.belframework.org/belframework/20150611/namespace/go-cellular-component.belns"
DEFINE NAMESPACE GOBP AS URL "http://resource.belframework.org/belframework/20150611/namespace/go-biological-process.belns"
DEFINE NAMESPACE CHEBI AS URL "http://resource.belframework.org/belframework/20150611/namespace/chebi.belns"

**Comment by cthoyt** [comment]
It was unclear in the spec if abundances can have locations... I guess that's a bit silly but the reason is that the parser isn't looking for a location tag so its getting a parser failure. I'll also add this in for 0.2.6
