### ISSUE TITLE
Fix HGVS Protein Truncation

### ISSUE THREAD

**Issue by cebel** [pybel/pybel#58]
valid BEL statement logs a **general parser failure** for  protein truncated by substitution of amino acid with a stop codon.

exmple (subject) p.41 pdf BEL 2.0 Specification 2014-06

p(HGNC:ABCA1, var(p.Arg1851*)) -- g(HGNC:ACE)

**Comment by cthoyt** [comment]
I figured out why this didn't work! The original example I read was `p.C40*` and I thought this meant that the `C` signified a truncation, so I hard-coded `C`. Turns out, this should be an amino acid code!
