### ISSUE TITLE
Switch unqualified edges to not use keys

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#61]
Don't set the key in `pybel.parser.parse_bel.BelParser.add_unqualified_edge` to maintain that all keys for all edges are integers assigned by the default edge key factory in `networkx`, and to make implementing the data models in `sqlalchemy` easier.

This means that there has to be a different way to check that an edge isn't in the graph. My first idea is to check `0 == len(g.edge[u][v])` but that might not be the right thing to do since it could also be possible to have other edges. 

Perhaps iterate over the list of edges in `0 == sum(1 for data for g.edge[u][v].values() if data['relation'] == target_relation)` or some variant of this. Check whether boolean operations, summation, or something else is fastest.

**Alternatively:**

Use `-1` as the key value since it's still an `int()`, it won't violate the rules of the database, and it shouldn't mess up the edge key factory.

Thoughts? @LeKono @cebel @NandithaMallesh

**Comment by cebel** [comment]
if we use negative integers then we need more then only -1 because we have more then one relation which will be added automatically by pybel. {-1:'transcribedTo',-2:'traslatedTo',-3:'componentOf',-4:'reactantOf',...} But: **YES**, this is a very good compromise if networkx and all databases can deal with that.

**Comment by cthoyt** [comment]
You would never have two of these relations between the same node, so I think `-1` is enough for the key. The information about the type of relation, will of course be in the node data under the key `relation`

**Comment by cebel** [comment]
OK, but then the combination of (node_from_id, node_to_id, edge_key) can not be used any more as primary key.

**Comment by cthoyt** [comment]
Why not? There's necessarily at most only one type of unqualified edge that can connect two entities. You would never have 'transcribedTo' between a Protein and a Complex, you could only ever have 'componentOf'

**Comment by cebel** [comment]
Why not using more negative identifiers to clearly identify a specific type of automatically added relation (without any context). This makes live much

**Comment by cebel** [comment]
easier for SQL queries.

**Comment by cebel** [comment]
And again: if you use always -1 for different automatically added relations (node_from_id, node_to_id, edge_key) is NO primary key, because -1 can stand for all automatically added relations
