### ISSUE TITLE
Validation checks for nodes and edges

### ISSUE THREAD

**Issue by cebel** [pybel/pybel#65]
Validate if
1. enzyme activity is described by the IUBMB EC classification system (http://www.chem.qmul.ac.uk/iubmb/)
2. a dbSNP RS identifier is correctly linked to a gene
3. substrates and products in a (bio-)chemical reaction are correct 
Please write comments if you have more suggestions

**Comment by cthoyt** [comment]
dbSNP's don't necessarily have to be linked to a gene to still be useful information. Knowing a SNP increases a disease is still useful knowledge... how should it be represented? For now, I don't think `geneAbundance` is incredibly useful for representing gene products and it's okay to stick any genetic-type stuff there (also includes chromosomal locations sans gene context)

**Comment by cebel** [comment]
3. substrates and products in a (bio-)chemical reaction are correct

**Comment by cthoyt** [comment]
You can edit the original post to add more stuff ^. This can help keep the chat organized :)

**Comment by cthoyt** [comment]
This issue is migrated to https://github.com/pybel/pybel-tools/issues/10
