### ISSUE TITLE
Convert tests from unittest to py.test

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#85]
py.test has a much more extensive framework and allows for parametric testing, which will allow for the unit and integration testing code to be much more concise and readable

**Comment by scolby33** [comment]
I disagree that py.test can do anything that unittest can't. However, I think unittest's philosophy of having class-based test cases is kinda old fashioned and agree that py.test is better.

But! Do you really want to change your tests? Remember what Raymond Hettinger said about that. There's no tests for the tests, so changing them is kinda risky.

**Comment by cthoyt** [comment]
I still want to figure out a reasonable way (without me implementing anything) to do parametric tests in unittest. You're right though, it's not a good idea to refactor at this point
