### ISSUE TITLE
Export to CX

### ISSUE THREAD

**Issue by cebel** [pybel/pybel#87]
Export to NDEx v1.3 – CX Data Model http://www.home.ndexbio.org/data-model/

**Comment by cthoyt** [comment]
Do they have any examples of BEL documents serialized to their format? This documentation hurts my eyes

**Comment by cebel** [comment]
I don't think so but the CX network exchange format that Deter Prat's group now use as the primary I/O from NDEx has an extensible schema - and currently has defined and documented extensions to support BEL evidence, citations, function terms, reified edges, namespaces and annotation definitions.

**Comment by cthoyt** [comment]
It looks like their link http://www.home.ndexbio.org/bel-support is dead

**Comment by cthoyt** [comment]
This issue is being taken care of in https://github.com/cthoyt/pybel2cx
