### ISSUE TITLE
Mutation test pybel.constants

### ISSUE THREAD

**Issue by cthoyt** [pybel/pybel#98]
Nothing should break if the values of the constants in `pybel.constants` are changed, because they are always referred to through the pybel source and testing code by their variable name.

The idea is to systematically change the values of each variable - one at a time, add garbage text to the end of the constant, and rerun the testing suite - and see if anything breaks. Nothing should, so if it does, that probably points to code where a value is used rather than the reference.

This would be a good issue for someone who doesn't know much about the project but wants to make a contribution!

**Comment by LeKono** [comment]
Maybe consider putting all constants in `constants.py`? 
For example the ones that are stored in `GmodParser`, `FragmentParser` and so on. Why are these constants not located in `constants.py`?

**Comment by cthoyt** [comment]
No reason. They were originally part of classes, but https://www.youtube.com/watch?v=o9pEzgHorH0, so now they're still in the same place because I never moved them

**Comment by cthoyt** [comment]
I think this is basically okay now
