### ISSUE TITLE
pybel import problem in python 2.7 (graph.__all__ )

### ISSUE THREAD

**Issue by cebel** [pybel/pybel#99]
branch: development

Seems to me that graph.__all__ is missing in python2.7. No problem in python 3.5. But that's strange because graph.__all__ exists.
```
In [1]: import pybel
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-bce5857d9ab2> in <module>()
----> 1 import pybel

/usr/local/lib/python2.7/dist-packages/pybel/__init__.py in <module>()
      8 from .manager import to_database, from_database
      9 
---> 10 __all__ = ['to_database', 'from_database', 'to_bel'] + graph.__all__ + io.__all__
     11 
     12 __version__ = '0.3.5-dev'

AttributeError: 'module' object has no attribute '__all__'
```

**Comment by cthoyt** [comment]
stay tuned. Use commit https://github.com/pybel/pybel/commit/c638c464f5bd435e0e7926b3e481953989324f4d for now. I shouldn't have been doing experimental stuff on the develop branch.

**Comment by cebel** [comment]
io is also not pushed into branch, but imported in graph_cache.py 
src/pybel/manager/graph_cache.py in line 3
```
from ..io import to_bytes, from_bytes
```

**Comment by cebel** [comment]
In fact it was my stupid error and not graph.\__all\__. I had an old io folder in my pybel workspace folder :-( which blocks the import ..io thing

**Comment by cthoyt** [comment]
Close?
